### PR TITLE
feat: redirection after variable edition ; commit after rebase master

### LINKED ISSUE #141: Link to Reconfigure after variable edition
Following #125, would be nice to be able to jump to the `deploy/new/reconfigure` page after successful variable edition. Could be via a button or clicking on a toast.

### PR DESCRIPTION
**Pull request by mdrutel**
#### Which issue(s) this PR fixes

Fixes #141 

#### Additional comments

I had to rename the file to .tsx to add code in the toast.
The style of the toast may (will) be done in another issue.

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by PaulFarault — CHANGES_REQUESTED** [review]
This is actually not a redirection, you should rather use `router.push(...)` to redirect the user.

**Review by PaulFarault — APPROVED** [review]
My bad, I mixed this issue with the #184 !

Seems enough for now, you should open a new issue to improve the toast's style. It's easy to miss the link with this implementation.

**Review by pvalentin01 — APPROVED** [review]
The toast's style may be improved in a new issue (as requested by @PaulFarault) to better show the link "configure a new deployment" like a button, and to better fit the size of the toast with the content.

**Comment by PaulFarault** [comment]
> The toast's style may be improved in a new issue (as requested by @PaulFarault) to better show the link "configure a new deployment" like a button, and to better fit the size of the toast with the content.

#186 has been created (thx @mdrutel) this PR is now ready to be merged

**Pull request merged**
