### PR TITLE
161 unauthenticated mode

### LINKED ISSUE #161: Unauthenticated mode
As for tdp-server, tdp-ui needs an unauthenticated mode for testing purpose and to create a lightweight dev environment.

Unauthenticated mode should be actionable from the `config.json` file. When activated, the login portal shouldn't be shown.

### PR DESCRIPTION
**Pull request by PaulFarault**
#### Which issue(s) this PR fixes

Fixes #161 

#### Additional comments

This PR may be improved by storing the user `profile` infos in Redux (#138).

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by PaulFarault** [comment]
@rpignolet I wonder if I should store the `skipAuth` as a config prop. Would it be better to have it as an environment variable?

Also, I wonder how to integrate it to the doc as in order to work, we have to specify the `DO_NOT_USE_IN_PRODUCTION_DISABLE_TOKEN_CHECK` env variable on tdp-server. Should we add a dedicated dev or test env? Or just a mention on the README?

**Comment by rpignolet** [comment]
In `tdp-server`, all config var can be defined as environment variable, I think it should be the same for `tdp-ui` but this is a generic feature, currently, if the `tdp-ui` config does not read environment variable, do not add it inside this PR.
You can add a mention inside the README if you want.

**Review by rpignolet — APPROVED** [review]

**Comment by leopaul36** [comment]
I enabled `DO_NOT_USE_IN_PRODUCTION_DISABLE_TOKEN_CHECK=True` in `env/dev/config/tdp_server.env` and the UI still tries to reach the OpenID, I can see in the console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/auth/realms/tdp_server/.well-known/openid-configuration. (Reason: CORS request did not succeed). Status code: (null).
```

Did I miss something?

**Comment by PaulFarault** [comment]
I can't reproduce it @leopaul36, did you set `skipAuth` to `true` in the UI's `config.json`? (Yes, it is not documented yet)

**Comment by PaulFarault** [comment]
Force pushed after rebase on master.

**Review by leopaul36 — APPROVED** [review]

**Pull request merged**
