### PR TITLE
Optimize variable edition and use of Monaco editor in raw mode

### LINKED ISSUE #96: Raw field using code editor
Raw field view can be rawer using tools like [monaco](https://github.com/microsoft/monaco-editor) for example.

### LINKED ISSUE #149: Can't restitute knox/gateway_topologies
`type error` when Knox - gateway_topology / tdpldap var is loaded.

### LINKED ISSUE #164: Variable edition state optimization
The user input of the form are stored in Redux. It would be better to store them in a local context (as it was in the first place, but keeping the reducers introduced by Redux), and then send it to Redux once validated.

Also, we must ensure that the variables that have been modified and then the modification canceled, are not send to the server. (as described in https://github.com/TOSIT-IO/tdp-ui/pull/157#issuecomment-1415863529).

### PR DESCRIPTION
**Pull request by PaulFarault**
#### Which issue(s) this PR fixes

Fixes #96 
Fixes #149 
Fixes #164

#### Additional comments

- Add [`react-hook-form`](https://react-hook-form.com/) to optimize state and to simplify the `userInput` slice. The slice now only contains dirty variables across a single service and is emptied when switching service.
- Sync variable edition in raw and view modes, with [Monaco](https://www.npmjs.com/package/@monaco-editor/react) as the raw code editor.
- Persist user settings across pages (raw/visual mode, show unused tabs).
- New variables can be added using raw mode. (#65)
- Variable deletion in raw mode.

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by PaulFarault** [comment]
Force pushed after rebase on master.

**Comment by PaulFarault** [comment]
Seems to be a problem with nested object from view => raw

**Comment by mdrutel** [comment]
Hi,
:question:  :x:  :white_check_mark:  :heavy_check_mark: 
:question: When you select the Knox service, the tdpldap variable from the group gateway_topology is empty in View mode.
But it is related to the issue #149.
:question: When you try to modify the attribute name, another variable is created instead.
:question: In Raw mode, when there's a syntax error, an unhandled error popup appears ; do we have to add a try/catch block ?
:question: If there's a syntax error, there's only an error in the console when you click on the Validate button.
:question: When you scroll down to the end of the text, only one line is displayed ; I prefer the behavior of a text editor
:question: when you add an array variable in Raw mode, in View mode you have another display :
image
image
:question: (maybe related to another issue) when you dislay an existing array, you have this : in Raw mode, then in View mode :
image
image

:heavy_check_mark: When you modify in Raw mode, the state is updated in View mode

**Comment by PaulFarault** [comment]
Overall, the raw view seems to be fixed now and the sync between view / raw is working. View mode has some problems but those are hard to solve without any JSON schema. The default mode is now the raw one. I'll add a mention on the view page that this is still a work in progress.

> When you try to modify the attribute name, another variable is created instead.

Yes that normal. Renaming a variable is not possible. Hence, it is the same as deleting/creating a new one.

> In Raw mode, when there's a syntax error, an unhandled error popup appears ; do we have to add a try/catch block ?

It seems to be fixed now. The problem now appear on visual mode.

> If there's a syntax error, there's only an error in the console when you click on the Validate button.

It seems to be fixed now.

> When you scroll down to the end of the text, only one line is displayed ; I prefer the behavior of a text editor

I'm not sure to understand this one.

> when you add an array variable in Raw mode, in View mode you have another display / (maybe related to another issue) when you dislay an existing array, you have this : in Raw mode, then in View mode

Arrays are causing some troubles. I decided to treat them as object until we make use of the json schemas.

**Comment by sergkudinov** [comment]
I found a bug. To reproduce, do:

1. Run tdp-server with docker, enabling `DO_NOT_USE_IN_PRODUCTION_DISABLE_TOKEN_CHECK=True`
2. Run tdp-ui with `"skipAuth": true` in config.json
3. Go to Spark service - http://localhost:3000/services/spark
4. Click on the "View" button
5. I outputs multiple errors:

```
A non-serializable value was detected in an action, in the path: `payload`. Value: FetchError: The request failed and the interceptors did not return an alternative response
Caused by: TypeError: NetworkError when attempting to fetch resource.
...
A non-serializable value was detected in the state, in the path: `variables.error`. Value: FetchError: The request failed and the interceptors did not return an alternative response
...
Uncaught TypeError: can't convert null to object
...
The above error occurred in the <VisualEditor> component:
VisualEditor@webpack-internal:///./src/components/Services/ServiceVariables/Editor/VisualEditor/index.tsx:98:51
...
```

**Comment by PaulFarault** [comment]
Thanks @sergkudinov! I fixed it on my last commit.

**Review by sergkudinov — APPROVED** [review]
Looks good to me, except [this](https://github.com/TOSIT-IO/tdp-ui/pull/191#issuecomment-1499032850) is not improved.

**Comment by PaulFarault** [comment]
> Looks good to me, except https://github.com/TOSIT-IO/tdp-ui/pull/191#issuecomment-1499032850 is not improved.

True, it doesn't seem to be any settings for this with Monaco.

**Comment by PaulFarault** [comment]
TODO :

- If there is no click outside Monaco, the value is not taken into account when validating
- Errors are display inside the console when JSON can't be parsed

**Comment by PaulFarault** [comment]
I fixed the bug that I mentioned previously.

Forced pushed to squash commits.

**Comment by mdrutel** [comment]
I tested the add/remove of a variable :
* Adding a variable : :heavy_check_mark: 
I get my variable
* Removing a variable : :x:
The variable is kept, and ```null``` is set

**Comment by PaulFarault** [comment]
> - Removing a variable : x
>   The variable is kept, and null is set

I did it on purpose. I understood from @rpignolet that deleted variables should be set as `null`. Does it seems good for you Romain or am I wrong?

**Comment by rpignolet** [comment]
Does the server support variable deletion by setting it to `null` ? If not, in the UI, removing variable should not be possible until the server support it.

**Comment by PaulFarault** [comment]
> If not, in the UI, removing variable should not be possible until the server support it.

It's a bit weird to prevent deleting in a raw mode but I can just ignore deleted lines for now. (They will reappear after validating)

**Review by sergkudinov — APPROVED** [review]
I ran and tested the edditor, it seams it works without issues descussed above. However, I see different errors in the browser console. I propose to merge to master as is, because existing errors must disapear after my refactoring to RTK Query this week.

**Review by mdrutel — APPROVED** [review]
test of the editore : OK

**Comment by rpignolet** [comment]
@PaulFarault 
If you put `null` for a variable, I don't know if it will actually write `null` to the YAML file for Ansible. Also how will Ansible interpret this `null`, will it still merge dicts?

Currently the server does not support variable deletion, setting a variable to `null` doesn't necessarily make sense so I would say ignore the deletion for now and display a message above the editor stating that it is not supported at this time.

When the server will officially support it we can do the implementation on the UI side. The UI must use existing features of the server and not seek to circumvent non-existent features of the server.

**Comment by PaulFarault** [comment]
This PR should fix the PUT behavior to allow deletion : https://github.com/TOSIT-IO/tdp-server/pull/122

I'll switch from PATCH to PUT in the next commit to handle variables deletion.

**Comment by sergkudinov** [comment]
It is fine from my side.

**Pull request merged**
