### PR TITLE
feat: hide unused component tabs

### LINKED ISSUE #122: Hide components that contains no variables
Service pages display a list of tabs with its components.

image

Most of them don't contain any value (ex: `yarn`>`ranger`). It would be clearer to hide them and to add a "show all" option, in case the user want to define a variable in an empty component.

### PR DESCRIPTION
**Pull request by PaulFarault**
#### Which issue(s) this PR fixes

Fixes #122 

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by gboutry — CHANGES_REQUESTED** [review]
The button to toggle display does not fit with the overall design of the page.

**Comment by gboutry** [comment]
Currently, it does not look like a button, and therefore it's not user friendly. Users must hover with their mouse to confirm that it's clickable. This is a bad UX

**Comment by PaulFarault** [comment]
Cursor switch to pointer when hovering. I can change the color to be darker when hovering if you think that's necessary.

We could also put it in blue later. At the moment I try to only use shades of grey to focus about contrast between components.

**Comment by gboutry** [comment]
IMO, they should be in the same style as the components. For me, the style does not define the component, but a button. But my interpretation could be wrong

**Comment by PaulFarault** [comment]
I understand, I still think that having a different style will be clearer:

image

image

**Review by gboutry — APPROVED** [review]
Is still thinks it's better, but since we won't reach a consensus I will not block this PR any longer.

**Review by leopaul36 — APPROVED** [review]

**Pull request merged**
