### PR TITLE
Refactor to RTK Query

### LINKED ISSUE #28: Async services with loading components
Would be nice to transform services (as get server status or get services list) as async function with a `isLoading` state. It'd allow us to display a loading component.

### LINKED ISSUE #112: Refactor to a useQuery hook
Calls to the server using the generated `@/tdp-client` are created in custom hooks among the code (`useServerInfos`, `useDeploy`...). They all need to implement the same states (`loading`, `error` and eventually `data`).

Would be nice to replace them with a global `useTdpClientQuery` hook which can take as arguments:

- `type`: an enum to select which endpoint to call
- `params`: parameters to pass to the endpoint call

### LINKED ISSUE #113: Refactor hooks used in components
As for the `DeployDag` and `DeployOperations` components, would be nice to improve the other components to make them contain their own hooks instead of putting them in the global `src/hooks`.

Among the components to refactor:

- `Menu`
- `DeployLogs`

### LINKED ISSUE #114: Refactor useTdpClient hook
The `useTdpClient` hook is currently in `src/context/`. Would be nice to move it to `src/hooks`.

### LINKED ISSUE #126: Missing cleanup function when fetching
Hooks that are fetching/posting data to the server must include a cleanup function.

### LINKED ISSUE #168: Redux log slices
Logs could be stored in a Redux slice.

### LINKED ISSUE #173: Pass TDP client API as a Redux middleware
Currently, an instance of the TDP client API is initialized (after authentication and config loading) and store in a context. To fetch data (variables for example):

1. The client is used directly inside the component
2. The fetch result is then passed to Redux
3. A selector is finally used to update the page based on the Redux store

It would be best to pass the client as a Redux middleware and to fetch data directly with Redux using thunks.

### PR DESCRIPTION
**Pull request by sergkudinov**
#### Which issue(s) this PR fixes

Fixes #173 
Fixes #112
Fixes #113
Fixes #114
Fixes #126
Fixes #168
Fixes #28

Replaces #201

#### Additional comments

It fully replaces the old way of querying the server and eliminates using OpenAPI generator on Java.

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by sergkudinov** [comment]
Just descovered a few issues:
- change env vars to config from the react state [here](https://github.com/TOSIT-IO/tdp-ui/blob/173-redux-rtk/src/features/api/emptyApi.ts#L22)
- when switching between companents on the service page, variables are not correctly changing in the Monaco edditor

**Comment by PaulFarault** [comment]
We should add `yarn.lock` and `package-lock.json` to the `.gitignore` until the first release at least.

**Comment by sergkudinov** [comment]
added lock files to gitignore

**Comment by PaulFarault** [comment]
Looks promising!!

If I'm not mistaken, it's missing:

- Authentication
- Remove the need for a `NEXT_PUBLIC_TDP_API_URL=http://localhost:8000` variable in the `.env` file

Do you see anything else to add / do you need some help?

---

Also, we may want to refactor it a bit (code is spited between `src/scripts/`, `src/features` and `src/store.ts`). Maybe we could put all Redux related code in a `src/store/` directory?

**Comment by PaulFarault** [comment]
I've checked previously opened issues. Your PR will:

Fixes #112 
Fixes #113 
Fixes #114 
Fixes #126 
Fixes #168
Fixes #173 (current)

**Comment by sergkudinov** [comment]
> I'm not sure that we should commit the /src/features/tdpApi.ts file as it is generated. We could [generate it programmatically](https://redux-toolkit.js.org/rtk-query/usage/code-generation#programmatic-usage) from the schema to ensure that the file is not altered.

I tried the programmatic usage, but it doesn't work for in browser environment. Check this [issue](https://github.com/reduxjs/redux-toolkit/issues/1784).

I think it is doesn't make a big sence commiting the genereated API in `src/features/api/tdpApi.ts` or not. We have a full control over the schema and it is stored in the same repository. Once it is changed, we regenerate the API and commit both. Git-ignoring it would just make the source code less dependent on instructions in the doc.

If we ignore, I would suggest:
- keeping `generate` script
- adding `postinstall` script calling `generate`

Example:
```
    ...
    "generate": "npx @rtk-query/codegen-openapi ./scripts/openapi-config.ts",
    "postinstall": "npm run generate"
    ...
```

**Comment by PaulFarault** [comment]
I'm not sure to understand the issue but you're right, that's not very important. The solution that you propose using the `postinstall` script would be enought!

Idk if we could have another opinion but IMO we shouldn't commit the generated output.

**Comment by sergkudinov** [comment]
Done:

[x] We may want to refactor it a bit (code is spited between src/scripts/, src/features and src/store.ts). Maybe we could put all Redux related code in a src/store/ directory?
[x] I'm not sure that we should commit the /src/features/tdpApi.ts file as it is generated.

**Comment by sergkudinov** [comment]
> when switching between components on a service page, variables are not correctly changing in the Monaco edditor

Fixed this. However, swithing beteween components is not smooth anymore. Didn't have time to improve it.
The was a problem of react rerendering when variables changes.

There is now an issue with validating. It is not working as expected. I'll continue next week on fixing it.

**Comment by sergkudinov** [comment]
> However, swithing beteween components is not smooth anymore.

Done

> There is now an issue with validating. It is not working as expected. 

Done

**Comment by sergkudinov** [comment]
@PaulFarault 
review please, it is ready

**Comment by PaulFarault** [comment]
I'll have a look at it. You still have some conflicts to resolve before merging it to master.

**Comment by sergkudinov** [comment]
rebased

**Comment by PaulFarault** [comment]
Seems like you involuntarily "broke" some previous features while rebasing, pagination doesn't seem to work as expected: https://github.com/TOSIT-IO/tdp-ui/pull/185

**Comment by sergkudinov** [comment]
> Seems like you involuntarily "broke" some previous features while rebasing, pagination doesn't seem to work as expected: https://github.com/TOSIT-IO/tdp-ui/pull/185

fixed

**Review by mdrutel — APPROVED** [review]
Elements tested :
- services variables edition : OK
- deployments : OK
- Deploy Log Details : OK

**Pull request merged**
