### PR TITLE
refactor: improve generate script

### LINKED ISSUE #194: Adapt generator.sh script to support air-gapped environment
In air-gapped environment, we manage the `openapi-generator-cli-6.2.0.jar` file differently. So there is no need for `wget` to download it.

My suggestion is to add `--skip-download` option to `generate.sh` script and an `if` construction. I would also refactor `FORCE_OPENAPI_GEN` into cli command option `-f`/`--force` to make it look more fancy (similar to [`setup.sh`](https://github.com/TOSIT-IO/tdp-getting-started/blob/master/scripts/setup.sh))

### PR DESCRIPTION
**Pull request by sergkudinov**
#### Which issue(s) this PR fixes

Fixes #194

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by PaulFarault** [comment]
Thx for your refactor! I'll try it as soon as possible.

However, I'm not sure that this PR is the good place to add a `CHANGELOG.md`

**Comment by sergkudinov** [comment]
oups, I was testing different things and affected the master
I am force pushing

**Comment by sergkudinov** [comment]
ready

**Comment by PaulFarault** [comment]
Everything seems to be working except the help (`-h`).

**Review by PaulFarault — APPROVED** [review]

**Review by rpignolet — APPROVED** [review]

**Pull request merged**
