### PR TITLE
feat: dev deploy logs wip

### LINKED ISSUE #54: Past deployment logs
A page should be made to browse logs from past deployments.

### PR DESCRIPTION
**Pull request by jpsavy**
#### Which issue(s) this PR fixes

Fixes #54

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by jpsavy** [comment]
image

**Review by PaulFarault — APPROVED** [review]

**Review by gboutry — CHANGES_REQUESTED** [review]
Good job.

IMO I find it weird having operation in desc order.

I believe the last operation should be at the end, it's more natural.

**Comment by PaulFarault** [comment]
> I believe the last operation should be at the end, it's more natural.

It seems more practical to have them in the other way when, for example, monitoring logs from an ongoing deployment.

We can invert the order for now and create an issue to add an "order" button later.

**Review by gboutry — APPROVED** [review]

**Comment by jpsavy** [comment]
The last operation is now at the end.

**Comment by jpsavy** [comment]
The "order" button will be add in the issue #104

**Pull request merged**
